baseURL: "https://jahnavi-ramagiri.github.io"
languageCode: "en-us"
title: "Jahnavi"
theme: master

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark
    color:
        secondaryBackgroundColor: "Blue"
    #darkmode:
        #secondaryBackgroundColor: "Blue"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #     textColor: "black"
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
      position: absolute
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi there! I'm "
    title: "Jahnavi Ramagiri"
    # subtitle: "Exploring the world of AI, one algorithm at a time."
    content: |-
      A passionate ML Engineer with a blend of Electronics and Computer Science. When I'm not diving deep into code, I love to Pen Poems and have a taste for Music.!

      I live in Washington, DC and call India my home.
    image: "images/me4.jpg"
    button:
      background - color:
      enable: true
      name: "Resume"
      url: "https://docs.google.com/document/d/1OPHBv8o1gvCH53SJ2upgUX0t6zT9yjYpStMYta0XuUY/edit?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/JahnaviRamagiri
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jahnaviramagiri/
        - icon: fab fa-instagram
          url: https://instagram.com/jahnaviramagiri?igshid=MzMyNGUyNmU2YQ%3D%3D&utm_source=qr
        - icon: fab fa-instagram
          url: https://instagram.com/sochconnect?igshid=cGRhbXhzcm1raDk2&utm_source=qr
      #customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I'm Open to work from May 2024"
    # image: "/images/me3.jpg"
    content: |-
      I am a second-year Computer Science master's student with a focus on Machine Learning and Data Science.
      Leveraging a strong foundation in these areas, I've spent the last three years as a Machine Learning Engineer and Software Development Engineer, contributing my expertise to the Automotive, BFSI, and healthcare domains.

      Skills:
        - Languages : Python, R, SQL
        - Libraries & Tools : Pytorch, Tensorflow, Pandas, Scikit-learn, NLTK, SpaCy, Gensim, Tableau, MLFlow, Kubernetes
        - ML & DL: CNNs,  Advanced Convolutions, Learning Rates, Embeddings, Transformers, LangChain
        - AWS - Sagemaker, Textract GCP - AutoML

    # skills:
    #   enable: true
    #   # items:
    #     # title: "Skills:"
    #   items: |-
    #     - Languages : Python, R, SQL
    #     - Libraries & Tools : Pytorch, Tensorflow, Pandas, Scikit-learn, NLTK, SpaCy, Gensim, Tableau, MLFlow, Kubernetes
    #     - ML & DL: CNNs,  Advanced Convolutions, Learning Rates, Embeddings, Transformers, LangChain
    #     - AWS - Sagemaker, Textract GCP - AutoML


  # Experience
  experience:
    enable: true
    items:
      - job: "Research Assistant, Prof. Murray Loew"
        company: "Medical Imaging and Image Analysis Laboratory, George Washington University"
        companyUrl: "https://loewlab.seas.gwu.edu/dr-loew/"
        date: " June 2023 - Present"
        info:
          enable: true
          content: "Location: Washington, DC "
        featuredLink:
          enable: true
          url: "https://loewlab.seas.gwu.edu/dr-loew/"
        content: |
          Washington, DC
          - Preprocessed Brain MRI scans on Sagittal, Coronal and Axial planes using Nibabel and Nipy Libraries.
          - Assisting in the implementation of algorithms, focusing on early detection of Alzheimer's disease to identify potential biomarkers.

      - job: "Machine Learning Fellow"
        company: "Launchpad AI (Remote)"
        companyUrl: "https://www.fellowship.ai/"
        date: "July 2023 - September 2023"
        info:
          enable: true
          content: "Location: Remote"
        featuredLink:
          enable: true
          url: "https://www.fellowship.ai/"
        # info:
        #   content:
        content: |
          - Successfully automated the end-to-end travel planning pipeline by implementing a hybrid LAM - Open AI powered travel assistant, leading to a remarkable 30% reduction in user time.
          - Pioneered the integration of AmadeusAPI to streamline booking processes, ensuring a seamless and user-friendly experience


      - job: "Machine Learning Engineer, BFSI R&D"
        company: "Quantiphi"
        companyUrl: "https://quantiphi.com/"
        date: " July 2021 - August 2022"
        info:
          enable: true
          content: "Location: Bangalore, India"
        featuredLink:
          enable: true
          url: "https://quantiphi.com/"
        info:
          content: Generated a revenue of $6,400 for the startup by offering one-on-one sessions during late/early hours from India for students in the USA, designing course structure and content.
        content: |-
          Bangalore, India
          - Developed classification and post-processing modules, elevating document classification pipeline performance from 0.69 to industry-best 0.95 F1. Utilized GCP AutoML, PyTorch, Kubernetes for model development and lifecycle management.
          - Optimized dataframes, with 50% reduction in runtime for the first-of-its-kind claim adjudication pipeline in the industry.
          - Utilized Hugging Face models, applying Bioclinical BERT to extract semantic relations  medical insurance loss descriptions.


      - job: "Software Development Engineer"
        company: " ZF  Technology Center India "
        companyUrl: "https://www.zf.com/india/en/home/home.html"
        date: "  July 2020 - June 2021"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        featuredLink:
          enable: false
          url: "https://www.zf.com/india/en/home/home.html"
        content: |-
          Hyderabad, India
          -Engineered MATLAB and Python scripts for Signal Analysis in HP & DT transmissions,  for BMW, JLR, FCA, and Audi.
          - Spearheaded the development of Jenkins-based DevOps pipeline, driving a significant 40% reduction in employee effort.
          - Consistently recognized as the highest-rated employee in the team.



  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Masters in Computer Science, Specialization in Machine Intelligence and Cognition"
        school:
          name: "George Washington University, Washington, DC"
          url: "https://www.gwu.edu/"
        date: "2022 - 2024"
        GPA: "3.95 out of 4.0"
        content: |-
            - Was a Teaching Assistant for Design and Analysis of Algorithms (CSCI 6212) at the School of Engineering and Sciences, GWU.
            - Worked as a Research Assistant to pre-process Bio-Medical Image data for training a U-Net Deep Learning Algorithm in the Machine Learning team at the Medical Imaging and Image Analysis Laboratory
            - Attended Grace Hopper 2023 Conference with University Scholarship
            - Course Work: Machine Learning, Computer Vision, Natural Language Processing, Time Series Analysis, Design & Analysis of Algorithms, Big Data Analytics, Database Systems.

            Extracurricular Activities
             - Lead - Google Developer Students Club : Leading GDSC in North America Region for 2023-24
             - Active member of George Hacks
      - title: "Bachelors in Engineering, Electronics and Communications"
        school:
          name: "Chaitanya Bharathi Institute of Technology, Hyderabad"
          url: "https://www.cbit.ac.in/"
        date: "2016 - 2020"
        GPA: "8.42 out of 10"
        content: |-
            - Won 2nd place All India in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
            - Executive Committee Head - Makers of India CBIT : Mentored 500+ students to build AI enabled  prototypes
            - Secretary - Engineers Without Borders CBIT: Established E-learning facilities in 50+ government schools in India  for economically deprived students alongside EWB-INDIA

  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      #- title: Smart India Hackathon 2020
       # content: Won 2nd place in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
        #url: "https://www.sih.gov.in"
      - title: TalentSprint Women Engineer’s Program 2019
        content: Top 125 nationwide in TalentSprint Women Engineer’s Program 2019  powered by Google.
      - title: Sudhee 2018, Chaitanya Bharathi Institute of Technology
        content: Secured consolation prize in Project Expo at Sudhee’18, National level Technical Symposium of CBIT for the project, “Automated Writing Machine”.
      - title: Sampurna E-Vidya App
        content: Presented on behalf of the club Engineers Without Borders, CBIT  and secured 3rd prize for “Sampurna E-Vidya App” at All India EWB Chapter’s Meet 2017 along with a seed amount of Rs.15000/-. # Conducted events virtually during COVID for effective engagement among new students.
      - title: Mission R&D
        content: 1 of 11 students who got selected for MRND (Mission R&D) from CBIT.

  # projects
  projects:
    enable: true
    items:
      - title: Image Captioning for Visually Impaired Individuals
        content: |-
          Image Captioning System to generate meaningful captions to aid visually impaired individuals.
        image: /images/projects/image_captioning.jpeg
        featured:
          name: Click here to know more!
          link: https://github.com/JahnaviRamagiri/image-caption-generator
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/shubhjadhav/image-caption-generator
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Walksafe - Pedestrian Safety for Washington DC
        content: |-
          Pedestrian Safety App with proximity Alert feature developed for Washington DC.
        image: /images/projects/pedestrian_safety.png
        # featured:
        #   name: Click here to know more!
        #   link: https://github.com/Keerthi-Sreenivas/Elon_Musk-Doge-Tweet_Analysis/blob/main/Facts_derived_from_the_study.pdf
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/Keerthi-Sreenivas/Elon_Musk-Doge-Tweet_Analysis

      - title: Monocular Depth Estimation and Background/Foreground Extraction - Computer Vision
        content: |-
          Prediction of depth map and Mask for the given foreground object.
        image: /images/projects/depth_estimation.jpeg
        featured:
          name: Click here to know more!
          link: https://github.com/JahnaviRamagiri/EVA-B2/tree/master/S15
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/JahnaviRamagiri/EVA-B2/tree/master/S15

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: jahnavi.ramagiri27@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/JahnaviRamagiri
      linkedin: https://www.linkedin.com/in/jahnaviramagiri/
    # twitter: https://twitter.com
      instagram: https://instagram.com/jahnaviramagiri?igshid=MzMyNGUyNmU2YQ%3D%3D&utm_source=qr
    # facebook: https://facebook.com
